[package]
name = "history-grep"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hg"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0", features = ["derive", "cargo"] }
dialoguer = "0.10.4"
